### ISSUE TITLE
ng serve hangs

### ISSUE THREAD

**Issue by vzemlys** [testing-angular-2-applications/chapter-4-starter#1]
After multitude of unmet peer dependencies I've managed to do a succesfull npm install, by changing dependencies of @angular to 2.2.3. After that running ng serve is stuck at 20% with the following output:

```
10% building modules 2/2 modules 0 active(node:29476) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/mpiktas/src/chapter-4-starter/src/app/app.module.ts, resolving symbol AppModule in /Users/mpiktas/src/chapter-4-starter/src/app/app.module.ts
 20% building modules 84/84 modules 0 active                                          
```

Any ideas? I am not that familiar with angular and really just want to run the examples and try to learn. 

I am using npm 3.10.8 and node 6.9.1 on Mac Os X.

**Comment by jesselpalmer** [comment]
I updated the dependencies, so it should be working ok now.  Go ahead and remove your old `chapter-4-starter`, then clone this repo again, cd inside of it and run `npm i`. After the dependencies have finished installing, try `ng s` and visit `localhost:4200`. If you still have any issues let me know.

**Comment by vzemlys** [comment]
Npm still complains with the following message:

```
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
```

However `ng serve` works.
